export type TypeColors =
  | 'white'
  | 'base-label'
  | 'base-button'
  | 'base-hover'
  | 'base-text'
  | 'base-subtitle'
  | 'base-title'
  | 'purple'
  | 'purple-light'
  | 'purple-dark'
  | 'yellow'
  | 'yellow-light'
  | 'yellow-dark'
